included:
  - OpenDispatchApp
  - Packages

excluded:
  - OpenDispatchApp/OpenDispatch.xcodeproj
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unused_import

line_length:
  warning: 140
  ignores_comments: true

identifier_name:
  min_length: 2
  excluded:
    - id

type_body_length:
  warning: 350

file_length:
  warning: 600
